"""add password auth columns to users

Revision ID: 12f25173a198
Revises: d4eea099a29c
Create Date: 2026-04-27 18:55:23.554713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12f25173a198'
down_revision: Union[str, Sequence[str], None] = 'd4eea099a29c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=256), nullable=True))
    op.add_column('users', sa.Column('name', sa.String(length=120), nullable=True))
    op.add_column('users', sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('users', 'cognito_sub',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'cognito_sub',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.drop_column('users', 'email_verified_at')
    op.drop_column('users', 'name')
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
