"""add subscribers table

Revision ID: 547bc1cb73ec
Revises: 1e47040eb444
Create Date: 2026-04-27 18:05:08.907139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '547bc1cb73ec'
down_revision: Union[str, Sequence[str], None] = '1e47040eb444'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscribers',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('whatsapp', 'expo_push', name='subscriber_kind'), nullable=False),
    sa.Column('target', sa.String(length=256), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'kind', 'target', name='uq_subscriber_owner_target')
    )
    op.create_index(op.f('ix_subscribers_owner_id'), 'subscribers', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscribers_owner_id'), table_name='subscribers')
    op.drop_table('subscribers')
    # ### end Alembic commands ###
