"""add custom_prompt to rules

Revision ID: c05fe3c81c36
Revises: c5b13235546e
Create Date: 2026-04-27 17:35:54.989138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c05fe3c81c36'
down_revision: Union[str, Sequence[str], None] = 'c5b13235546e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rules', sa.Column('custom_prompt', sa.String(length=4000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rules', 'custom_prompt')
    # ### end Alembic commands ###
